[tool.poetry]
name = "mail"
version = "0.1.0"
description = ""
authors = ["Dove <doveliu0516@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
aiosmtplib = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
